context:
  version: "22.2.1"

package:
  name: angular-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular/cli/-/cli-${{ version }}.tgz
  sha256: 797ab1bf9caca4c8a1c2bc3750b984f27ec24142c31fb491fdb9ccaf2c3522eb

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ng --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI tool for Angular
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
