context:
  version: "20.3.10"

package:
  name: angular-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular/cli/-/cli-${{ version }}.tgz
  sha256: f6153ad3f1b302c97a82168559c2474e8f5f758fbb4a0b09d187cb1766d3f51f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ng --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI tool for Angular
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
