context:
  version: 10.1.2

package:
  name: angular-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular/cli/-/cli-${{ version }}.tgz
  sha256: d439c49b179a3da8c482ffe93b3b27a2b2ba78a9a2c2b373b5790c56ccbc27ae

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ng --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI tool for Angular
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
