context:
  version: "21.2.4"

package:
  name: angular-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular/cli/-/cli-${{ version }}.tgz
  sha256: 5259d1f79575ba9278e6dd7daf984a057d13c25649f896322fb1bf8ebb728ff8

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ng --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI tool for Angular
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
