context:
  version: "22.0.0"

package:
  name: angular-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@angular/cli/-/cli-${{ version }}.tgz
  sha256: 34d69947c77bac413f6d6c4d1e0b9a2fd2980500af79483d1080f09677617da3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - ng --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CLI tool for Angular
  homepage: https://github.com/angular/angular-cli
  repository: https://github.com/angular/angular-cli

extra:
  recipe-maintainers:
    - danielnachun
